# fly.toml app configuration file generated for dani-astro-portfolio-blog-dawn-sun-2034 on 2024-12-06T16:05:19-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dani-astro-portfolio-blog-dawn-sun-2034'
primary_region = 'yul'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
