name: Carbon-Aware Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Fly.io CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "$HOME/.fly/bin" >> $GITHUB_PATH
          export PATH="$HOME/.fly/bin:$PATH"

      - name: Get Low-Carbon Fly.io Region
        id: carbonaware
        env:
          CARBON_API_TOKEN_ID: ${{ secrets.CARBON_API_TOKEN_ID }}
          CARBON_API_TOKEN_SECRET: ${{ secrets.CARBON_API_TOKEN_SECRET }}
        run: |
          # Query Carbon Aware API with credentials
          RESPONSE=$(curl -s -u "$CARBON_API_TOKEN_ID:$CARBON_API_TOKEN_SECRET" \
            "https://api.carbonaware.cloud/v1/by-provider/fly")

          # Extract the region with the lowest intensity
          CLEAN_REGION=$(echo "$RESPONSE" | jq -r '.regions | sort_by(.intensity) | .[0].id')
          echo "CLEAN_REGION=$CLEAN_REGION" >> $GITHUB_ENV

      - name: Deploy to Fly.io in Low-Carbon Region
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          echo "Deploying to region: $CLEAN_REGION"
          flyctl deploy --region $CLEAN_REGION
