name: Carbon-Aware Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest  

    concurrency: deploy-group  # Optional: prevent parallel deployments

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Build Astro Site
        run: npm run build  # Generate static files in 'dist/'

      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Get Low-Carbon Fly.io Region
        id: carbonaware
        env:
          CARBON_API_TOKEN_ID: ${{ secrets.CARBON_API_TOKEN_ID }}
          CARBON_API_TOKEN_SECRET: ${{ secrets.CARBON_API_TOKEN_SECRET }}
        run: |
          RESPONSE=$(curl -s -u "$CARBON_API_TOKEN_ID:$CARBON_API_TOKEN_SECRET" \
            "https://api.carbonaware.cloud/v1/by-provider/fly")
          CLEAN_REGION=$(echo "$RESPONSE" | jq -r '.regions | sort_by(.intensity) | .[0].id')
          echo "CLEAN_REGION=$CLEAN_REGION" >> $GITHUB_ENV

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only --regions $CLEAN_REGION --buildpack static
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
