name: Carbon-Aware Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: carbonrunner-2vcpu-ubuntu-latest  # Use CarbonRunner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Fly.io CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          export PATH="$HOME/.fly/bin:$PATH"

      - name: Get Low-Carbon Region
        id: carbonaware
        run: |
          CLEAN_REGION=$(curl -s "https://api.carbonaware.cloud/v1/by-provider/fly" | jq -r '.[0].location')
          echo "CLEAN_REGION=$CLEAN_REGION" >> $GITHUB_ENV

      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          echo "Deploying to region: $CLEAN_REGION"
          flyctl deploy --region $CLEAN_REGION
